progressBar completed
CalNourish/pantry-webapp pull request #100
Opened 2022-10-08 00:12 UTC by kxllytrxn

2022-10-08 21:49 UTC, janiseliang requested changes
looks good! just a few quick changes, and then we'll check with staff to get their opinion

2022-10-08 21:49 UTC, janiseliang commented on package.json
> +    "@ramonak/react-progress-bar": "^5.0.2",
delete both of these lines? it doesn't seem like you're using the react-progress-bar i think

2022-10-08 21:49 UTC, janiseliang commented on pages/order.js
> +  console.log(formStep);
delete

2022-10-08 21:49 UTC, janiseliang commented on pages/order.js
>    // TODO: add progress indicator
this is done now - can delete the TODO

2022-10-21 23:23 UTC, justinazhang approved these changes

2022-10-21 23:25 UTC, justinazhang approved these changes

2022-10-21 23:26 UTC, merged