Resolved Issue #92  -  UI is complete with Tailwind and Firebase updates.
CalNourish/pantry-webapp pull request #118
Opened 2022-12-03 00:32 UTC by martinezdavid12

2022-12-03 00:32 UTC, martinezdavid12 commented
I pulled the latest version and integrated my changes to the adminPage.js. Then, I created this branch to track the changes and compare for the pull request.

2022-12-23 20:46 UTC, janiseliang requested changes
some small changes requested:

* visual changes: move "submit" button into left column. increase width of input field to full box width.
* user feedback: add some indication that the user/email addition worked. should be similar to the checkmark or X for the google sheet links boxes

2023-01-14 08:44 UTC, janiseliang commented
ccurrently working on doing the small UI changes and merging with #123
-janise

2023-01-14 12:03 UTC, janiseliang approved these changes

2023-01-14 12:04 UTC, merged