Checkout frontend
CalNourish/pantry-webapp pull request #24
Opened 2021-11-01 03:52 UTC by janiseliang

Adds ./checkout page to site. Front end for #15.

Also added a `h-0` class to the parent div in `components/Layout.js`. Adding an explicit height to the container allows child components to use `h-full` (height: 100%) correctly. This _should_ not cause any negative effects on other pages.
Based on suggestion here: https://stackoverflow.com/a/21836870/12132573

2021-11-02 01:21 UTC, samuelwshen commented
Looked really good when I saw it! Can you post a screenshot of the page?

2021-11-02 01:22 UTC, jschnapper commented on pages/checkout.js
> +      // console.log(`Invalid barcode: ${barcode}`)
delete if not needed

2021-11-02 01:22 UTC, jschnapper commented on pages/checkout.js
> +    }
please delete if not needed

2021-11-02 01:24 UTC, jschnapper requested changes
Clean and nice use of comments 👍 good find on the layout update -- just remove some of those commented out pieces of code and i think you're good to merge

2021-11-02 01:29 UTC, janiseliang commented
> Looked really good when I saw it! Can you post a screenshot of the page?

![image](https://user-images.githubusercontent.com/44278227/139772036-a9331b02-86f1-417a-9c3c-76dcd613864e.png)
![image](https://user-images.githubusercontent.com/44278227/139772123-42a8ed54-0b31-45d0-ae90-765d2f17336d.png)

2021-11-05 01:03 UTC, jschnapper approved these changes

2021-11-05 02:24 UTC, merged